att_r: 0
att_p: 0
att_y: 0
thrust_sp: 0.45

pos_x_sp: 0
pos_y_sp: 0
height_sp: 0.8
yaw_sp: 0

position_controller_P: 0.5
position_controller_I: 0
position_controller_D: 0.12

height_hover_P: 0.2
height_hover_I: 0.015
height_hover_D: 0.06

vicon_yaw_sp: 1.5708

traj_yaw_sp: 0
