ball_cutoff_line_x: -1.7
car_cutoff_line_x: -1.6
timer_threshold: 2

z_sp_update: 0.5 

att_r: 0
att_p: 0
att_y: 0
thrust_sp: 0.45

pos_x_sp: 0
pos_y_sp: 0

height_sp: 1
yaw_sp: 0

position_controller_P: 0.25
position_controller_D: 0.2

velocity_controller_P: 0.3
velocity_controller_D: 0.08


position_controller_x_P: 0.3
position_controller_x_D: 0.08

position_controller_y_P: 0.3
position_controller_y_D: 0.08

height_hover_P: 0.7
height_hover_I: 0.0
height_hover_D: 0.15

vicon_yaw_sp: 1.5708

traj_yaw_sp: 0

hover_thrust: 0.9

min_thrust: 0.6
max_thrust: 1

x_sp: 1.1
y_sp: 1

attitude_threshold: 0.6
