att_r: 0
att_p: 0
att_y: 0
thrust_sp: 0

pos_x: 0
pos_y: 0
height_sp: 0.3
height_vel_sp: 0.05
yaw_sp: 0

pos_hover_P: 0
pos_hover_I: 0
pos_hover_D: 0

height_hover_P: 1
height_hover_I: 0
height_hover_D: 0

height_hover_vel_P: 1
height_hover_vel_I: 0
height_hover_vel_D: 0

